# Generated by Django 4.2.3 on 2023-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('breed', models.CharField(max_length=75)),
                ('location', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
            ],
        ),
    ]
